# Generated by Django 5.2.12 on 2026-03-28 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_notificacao_tipos_rh'),
        ('rh', '0010_metas_pdi_enps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da conta')),
                ('tipo', models.CharField(choices=[('corrente', 'Conta corrente'), ('poupanca', 'Poupanca'), ('pagamento', 'Conta de pagamento'), ('caixa', 'Caixa')], max_length=10, verbose_name='Tipo')),
                ('banco', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, max_length=20, verbose_name='Agencia')),
                ('numero', models.CharField(blank=True, max_length=30, verbose_name='Numero da conta')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, help_text='Saldo na data de abertura no sistema', max_digits=12, verbose_name='Saldo inicial')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conta bancaria',
                'verbose_name_plural': 'Contas bancarias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=7, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='financeiro.categoriafinanceira', verbose_name='Categoria pai')),
            ],
            options={
                'verbose_name': 'Categoria financeira',
                'verbose_name_plural': 'Categorias financeiras',
                'ordering': ['tipo', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=7, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descricao')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor bruto')),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, help_text='Apos taxas do gateway (se aplicavel)', max_digits=12, null=True, verbose_name='Valor liquido')),
                ('canal', models.CharField(choices=[('manual', 'Manual'), ('pix', 'Pix'), ('ted', 'TED / DOC'), ('boleto', 'Boleto'), ('cartao', 'Cartao'), ('dinheiro', 'Dinheiro'), ('gateway', 'Gateway (Asaas)'), ('sistema', 'Gerado pelo sistema')], default='manual', max_length=10, verbose_name='Canal de origem')),
                ('data_vencimento', models.DateField(verbose_name='Data de vencimento')),
                ('data_competencia', models.DateField(blank=True, help_text='Regime de competencia (fato gerador)', null=True, verbose_name='Data de competencia')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('status', models.CharField(choices=[('previsto', 'Previsto'), ('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=10, verbose_name='Status')),
                ('id_externo', models.CharField(blank=True, help_text='Para rastreabilidade com sistemas externos', max_length=100, verbose_name='ID externo (gateway)')),
                ('observacao', models.TextField(blank=True, verbose_name='Observacao')),
                ('comprovante', models.FileField(blank=True, upload_to='financeiro/comprovantes/%Y/%m/', verbose_name='Comprovante')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.categoriafinanceira', verbose_name='Categoria')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='crm.cliente', verbose_name='Cliente vinculado')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.contabancaria', verbose_name='Conta bancaria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='rh.departamento', verbose_name='Centro de custo')),
                ('parceiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='crm.entidadeparceira', verbose_name='Parceiro vinculado')),
            ],
            options={
                'verbose_name': 'Lancamento',
                'verbose_name_plural': 'Lancamentos',
                'ordering': ['-data_vencimento', '-criado_em'],
            },
        ),
    ]
