# Generated by Django 5.2.12 on 2026-03-28 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_notificacao_tipos_rh'),
        ('financeiro', '0002_seed_categorias_contas'),
        ('rh', '0010_metas_pdi_enps'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('emitida', 'Emitida (para cliente)'), ('recebida', 'Recebida (de fornecedor)')], max_length=8, verbose_name='Tipo')),
                ('numero', models.CharField(max_length=50, verbose_name='Número da NF')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('data_emissao', models.DateField(verbose_name='Data de emissão')),
                ('fornecedor', models.CharField(blank=True, max_length=200, verbose_name='Fornecedor')),
                ('arquivo', models.FileField(blank=True, upload_to='financeiro/nfs/%Y/%m/', verbose_name='Arquivo (PDF)')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='crm.cliente', verbose_name='Cliente')),
                ('lancamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='financeiro.lancamento', verbose_name='Lançamento vinculado')),
            ],
            options={
                'verbose_name': 'Nota fiscal',
                'verbose_name_plural': 'Notas fiscais',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=200, verbose_name='Fornecedor / Beneficiário')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('recorrencia', models.CharField(choices=[('unico', 'Único'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], default='unico', max_length=11, verbose_name='Recorrência')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='agendado', max_length=10, verbose_name='Status')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('comprovante', models.FileField(blank=True, upload_to='financeiro/comprovantes_desp/%Y/%m/', verbose_name='Comprovante')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='financeiro.categoriafinanceira', verbose_name='Categoria')),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='financeiro.contabancaria', verbose_name='Conta de pagamento')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='rh.departamento', verbose_name='Centro de custo')),
                ('lancamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesa_origem', to='financeiro.lancamento', verbose_name='Lançamento gerado')),
                ('nota_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='financeiro.notafiscal', verbose_name='NF vinculada')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-vencimento'],
            },
        ),
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('implantacao', 'Implantação'), ('mensalidade', 'Mensalidade'), ('avulsa', 'Avulsa (projeto/consultoria)'), ('parcelada', 'Parcelada')], max_length=12, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='pendente', max_length=10, verbose_name='Status')),
                ('canal', models.CharField(choices=[('manual', 'Manual'), ('pix', 'Pix'), ('ted', 'TED / DOC'), ('boleto', 'Boleto'), ('cartao', 'Cartao'), ('dinheiro', 'Dinheiro'), ('gateway', 'Gateway (Asaas)'), ('sistema', 'Gerado pelo sistema')], default='manual', max_length=10, verbose_name='Canal de cobrança')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='crm.cliente', verbose_name='Cliente')),
                ('lancamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobranca_origem', to='financeiro.lancamento', verbose_name='Lançamento gerado')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobrancas', to='crm.plano', verbose_name='Plano vinculado')),
                ('nota_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobrancas', to='financeiro.notafiscal', verbose_name='NF vinculada')),
            ],
            options={
                'verbose_name': 'Cobrança',
                'verbose_name_plural': 'Cobranças',
                'ordering': ['-vencimento'],
            },
        ),
    ]
