# Generated by Django 5.2.12 on 2026-03-28 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_cobranca_despesa_nf'),
        ('rh', '0010_metas_pdi_enps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ex: DAS, ISS, IRPJ, CSLL, PIS, COFINS, INSS patronal', max_length=100, verbose_name='Tipo de tributo')),
                ('competencia', models.DateField(help_text='Período de referência (1o dia do mês)', verbose_name='Competência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('numero_guia', models.CharField(blank=True, max_length=100, verbose_name='Número da guia / DARF')),
                ('status', models.CharField(choices=[('a_vencer', 'A vencer'), ('pago', 'Pago'), ('vencido', 'Vencido')], default='a_vencer', max_length=10, verbose_name='Status')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('comprovante', models.FileField(blank=True, upload_to='financeiro/tributos/%Y/%m/', verbose_name='Comprovante')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tributos', to='financeiro.contabancaria', verbose_name='Conta de pagamento')),
                ('lancamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tributo_origem', to='financeiro.lancamento', verbose_name='Lançamento gerado')),
            ],
            options={
                'verbose_name': 'Tributo',
                'verbose_name_plural': 'Tributos',
                'ordering': ['-vencimento'],
            },
        ),
        migrations.CreateModel(
            name='FolhaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('salario', 'Salário'), ('pro_labore', 'Pró-labore'), ('bonus', 'Bônus / Gratificação')], max_length=10, verbose_name='Tipo')),
                ('competencia', models.DateField(help_text='Usar o 1o dia do mês de referência', verbose_name='Competência (mês/ano)')),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor bruto')),
                ('desconto_inss', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto INSS')),
                ('desconto_ir', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto IR')),
                ('outros_descontos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Outros descontos')),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor líquido')),
                ('status', models.CharField(choices=[('calculado', 'Calculado'), ('aprovado', 'Aprovado'), ('pago', 'Pago')], default='calculado', max_length=10, verbose_name='Status')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folhas', to='rh.colaborador', verbose_name='Colaborador')),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folhas', to='financeiro.contabancaria', verbose_name='Conta de pagamento')),
                ('lancamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folha_origem', to='financeiro.lancamento', verbose_name='Lançamento gerado')),
            ],
            options={
                'verbose_name': 'Folha de pagamento',
                'verbose_name_plural': 'Folhas de pagamento',
                'ordering': ['-competencia', 'colaborador__nome_completo'],
                'unique_together': {('colaborador', 'tipo', 'competencia')},
            },
        ),
    ]
