# Generated by Django 5.2.12 on 2026-03-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_folha_tributo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folhapagamento',
            name='tipo',
            field=models.CharField(choices=[('salario', 'Salário'), ('pro_labore', 'Pró-labore'), ('pagamento_pj', 'Pagamento PJ'), ('comissao', 'Comissão'), ('bonus', 'Bônus / Gratificação'), ('13o', '13º Salário'), ('ferias', 'Férias'), ('adiantamento', 'Adiantamento'), ('rescisao', 'Rescisão')], max_length=15, verbose_name='Tipo'),
        ),
    ]
