# Generated by Django 5.2.12 on 2026-03-28 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_folha_tipos_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_pagamento', models.PositiveSmallIntegerField(default=5, help_text='Ex: 5 = quinto dia util do mes', verbose_name='Dia util para pagamento')),
                ('gerar_salario', models.BooleanField(default=True, verbose_name='Gerar salários CLT automaticamente')),
                ('gerar_pj', models.BooleanField(default=True, verbose_name='Gerar pagamentos PJ automaticamente')),
                ('gerar_pro_labore', models.BooleanField(default=True, verbose_name='Gerar pró-labore automaticamente')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conta_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contabancaria', verbose_name='Conta padrão para pagamentos')),
            ],
            options={
                'verbose_name': 'Configuração de folha',
                'verbose_name_plural': 'Configuração de folha',
            },
        ),
    ]
