# Generated by Django 5.2.12 on 2026-03-28 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_configuracao_folha'),
        ('rh', '0010_metas_pdi_enps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do ativo')),
                ('tipo', models.CharField(choices=[('equipamento', 'Equipamento de informática'), ('software', 'Licença de software'), ('moveis', 'Móveis e utensílios'), ('veiculo', 'Veículo'), ('outro', 'Outro')], max_length=12, verbose_name='Tipo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Nº de série / Identificador')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de compra (R$)')),
                ('data_aquisicao', models.DateField(verbose_name='Data de aquisição')),
                ('vida_util_anos', models.PositiveSmallIntegerField(default=5, verbose_name='Vida útil estimada (anos)')),
                ('taxa_depreciacao', models.DecimalField(decimal_places=2, default=20, help_text='Ex: 20% ao ano para equipamentos de informática', max_digits=5, verbose_name='Taxa de depreciação anual (%)')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('depreciado', 'Totalmente depreciado'), ('baixado', 'Baixado')], default='ativo', max_length=10, verbose_name='Status')),
                ('responsavel', models.CharField(blank=True, max_length=200, verbose_name='Responsável / Localização')),
                ('data_baixa', models.DateField(blank=True, null=True, verbose_name='Data de baixa')),
                ('motivo_baixa', models.CharField(blank=True, help_text='Venda, descarte, perda, etc.', max_length=200, verbose_name='Motivo da baixa')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativos', to='rh.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['-data_aquisicao'],
            },
        ),
    ]
