# Generated by Django 5.2.12 on 2026-03-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_ativo_patrimonio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='categoria',
            field=models.CharField(choices=[('imovel', 'Bem imóvel'), ('movel_duravel', 'Bem móvel durável'), ('movel_consumo', 'Bem móvel de consumo')], default='movel_duravel', max_length=15, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('depreciado', 'Totalmente depreciado'), ('baixado', 'Baixado'), ('consumido', 'Consumido')], default='ativo', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='tipo',
            field=models.CharField(choices=[('sala_comercial', 'Sala comercial'), ('terreno', 'Terreno'), ('galpao', 'Galpão'), ('equipamento', 'Equipamento de informática'), ('software', 'Licença de software'), ('moveis', 'Móveis e utensílios'), ('veiculo', 'Veículo'), ('mat_escritorio', 'Material de escritório'), ('mat_informatica', 'Material de informática'), ('outro', 'Outro')], max_length=15, verbose_name='Tipo'),
        ),
    ]
