# Generated by Django 5.2.12 on 2026-03-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_ativo_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='tipo',
            field=models.CharField(help_text='Ex: Notebook, Monitor, Licença Adobe, Mesa, Veículo', max_length=100, verbose_name='Tipo'),
        ),
    ]
