# Generated by Django 5.2.12 on 2026-03-28 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_ativo_tipo_livre'),
        ('rh', '0010_metas_pdi_enps'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativos', to='rh.setor', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='responsavel',
            field=models.CharField(blank=True, max_length=200, verbose_name='Responsável'),
        ),
    ]
