# Generated by Django 5.2.12 on 2026-03-28 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_ativo_setor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogExportacaoFolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Competência')),
                ('formato', models.CharField(max_length=4, verbose_name='Formato')),
                ('total_registros', models.PositiveIntegerField(verbose_name='Total de registros')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor total')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('exportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exportacoes_folha', to=settings.AUTH_USER_MODEL, verbose_name='Exportado por')),
            ],
            options={
                'verbose_name': 'Log de exportação da folha',
                'verbose_name_plural': 'Logs de exportação da folha',
                'ordering': ['-criado_em'],
            },
        ),
    ]
