# Generated by Django 5.2.12 on 2026-03-29 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_notificacao_tipos_rh'),
        ('financeiro', '0011_log_exportacao_folha'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaAsaas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asaas_id', models.CharField(help_text='Ex: sub_xxxx', max_length=50, unique=True, verbose_name='ID no Asaas')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('ciclo', models.CharField(choices=[('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quinzenal'), ('MONTHLY', 'Mensal'), ('QUARTERLY', 'Trimestral'), ('SEMIANNUALLY', 'Semestral'), ('YEARLY', 'Anual')], max_length=15, verbose_name='Ciclo')),
                ('proximo_vencimento', models.DateField(blank=True, null=True, verbose_name='Próximo vencimento')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('INACTIVE', 'Inativa'), ('EXPIRED', 'Expirada')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('billing_type', models.CharField(blank=True, help_text='BOLETO, PIX, CREDIT_CARD, etc.', max_length=20, verbose_name='Forma de pagamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas_asaas', to='crm.cliente', verbose_name='Cliente')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_asaas', to='crm.plano', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Assinatura Asaas',
                'verbose_name_plural': 'Assinaturas Asaas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ClienteAsaas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asaas_id', models.CharField(help_text='Ex: cus_xxxx', max_length=50, unique=True, verbose_name='ID no Asaas')),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asaas', to='crm.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cliente Asaas',
                'verbose_name_plural': 'Clientes Asaas',
            },
        ),
        migrations.CreateModel(
            name='CobrancaAsaas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asaas_id', models.CharField(help_text='Ex: pay_xxxx', max_length=50, unique=True, verbose_name='ID no Asaas')),
                ('tipo', models.CharField(choices=[('implantacao', 'Implantação'), ('mensalidade', 'Mensalidade'), ('avulsa', 'Avulsa')], max_length=15, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, help_text='Após taxas do Asaas', max_digits=10, null=True, verbose_name='Valor líquido')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('status', models.CharField(max_length=40, verbose_name='Status Asaas')),
                ('billing_type', models.CharField(blank=True, max_length=20, verbose_name='Forma de pagamento')),
                ('invoice_url', models.URLField(blank=True, verbose_name='URL do boleto/fatura')),
                ('bank_slip_url', models.URLField(blank=True, verbose_name='URL do boleto bancário')),
                ('pago_em', models.DateField(blank=True, null=True, verbose_name='Pago em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('assinatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobrancas', to='financeiro.assinaturaasaas', verbose_name='Assinatura')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas_asaas', to='crm.cliente', verbose_name='Cliente')),
                ('cobranca', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asaas', to='financeiro.cobranca', verbose_name='Cobrança vinculada')),
                ('lancamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobranca_asaas', to='financeiro.lancamento', verbose_name='Lançamento gerado')),
            ],
            options={
                'verbose_name': 'Cobrança Asaas',
                'verbose_name_plural': 'Cobranças Asaas',
                'ordering': ['-vencimento'],
            },
        ),
        migrations.CreateModel(
            name='EventoWebhookAsaas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=60, verbose_name='Evento')),
                ('asaas_payment_id', models.CharField(blank=True, max_length=50, verbose_name='Payment ID')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('processado', models.BooleanField(default=False, verbose_name='Processado')),
                ('erro', models.TextField(blank=True, verbose_name='Erro')),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento Webhook Asaas',
                'verbose_name_plural': 'Eventos Webhook Asaas',
                'ordering': ['-recebido_em'],
                'indexes': [models.Index(fields=['asaas_payment_id', 'processado'], name='financeiro__asaas_p_dded55_idx')],
            },
        ),
    ]
