# Generated by Django 5.2.12 on 2026-03-29 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_gateway_asaas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=20, verbose_name='Ação')),
                ('detalhes', models.TextField(verbose_name='Detalhes da alteração')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='financeiro.lancamento', verbose_name='Lançamento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Auditoria de lançamento',
                'verbose_name_plural': 'Auditorias de lançamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
