# Generated by Django 5.2.12 on 2026-03-26 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='crm.entidadeparceira')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='crm.produtocontratado')),
            ],
            options={
                'verbose_name': 'Comissão',
                'verbose_name_plural': 'Comissões',
                'ordering': ['-gerado_em'],
            },
        ),
    ]
