# Generated by Django 5.2.12 on 2026-03-27 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do cargo')),
                ('nivel', models.CharField(choices=[('diretor', 'Diretor'), ('gerente', 'Gerente'), ('especialista', 'Especialista'), ('analista', 'Analista'), ('assistente', 'Assistente'), ('estagiario', 'Estagiario')], default='analista', max_length=20, verbose_name='Nivel hierarquico')),
                ('faixa_salarial_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Faixa salarial minima')),
                ('faixa_salarial_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Faixa salarial maxima')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao de responsabilidades')),
                ('requisitos', models.TextField(blank=True, verbose_name='Requisitos minimos')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['departamento__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email_pessoal', models.EmailField(max_length=254, verbose_name='E-mail pessoal')),
                ('contato_emergencia_nome', models.CharField(blank=True, max_length=200, verbose_name='Contato de emergencia — nome')),
                ('contato_emergencia_telefone', models.CharField(blank=True, max_length=20, verbose_name='Contato de emergencia — telefone')),
                ('tipo_contrato', models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ')], max_length=3, verbose_name='Tipo de contrato')),
                ('data_admissao', models.DateField(verbose_name='Data de admissao')),
                ('data_desligamento', models.DateField(blank=True, null=True, verbose_name='Data de desligamento')),
                ('remuneracao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Remuneracao atual (R$)')),
                ('carga_horaria_semanal', models.PositiveSmallIntegerField(default=40, verbose_name='Carga horaria semanal (h)')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('afastado', 'Afastado'), ('desligado', 'Desligado')], default='ativo', max_length=10, verbose_name='Status')),
                ('pis_nit', models.CharField(blank=True, max_length=20, verbose_name='PIS / NIT')),
                ('ctps_numero', models.CharField(blank=True, max_length=20, verbose_name='CTPS — numero')),
                ('ctps_serie', models.CharField(blank=True, max_length=10, verbose_name='CTPS — serie')),
                ('banco_deposito', models.CharField(blank=True, max_length=100, verbose_name='Banco para deposito de salario')),
                ('regime_trabalho', models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Hibrido')], max_length=12, verbose_name='Regime de trabalho')),
                ('cnpj_pj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ ou CPF (MEI)')),
                ('razao_social', models.CharField(blank=True, max_length=200, verbose_name='Razao social')),
                ('banco_pagamento_pj', models.CharField(blank=True, max_length=100, verbose_name='Banco para pagamento PJ')),
                ('chave_pix', models.CharField(blank=True, max_length=100, verbose_name='Chave Pix')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='rh.cargo', verbose_name='Cargo')),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador', to='crm.endereco', verbose_name='Endereco')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador', to=settings.AUTH_USER_MODEL, verbose_name='Usuario do sistema')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='rh.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='rh.departamento', verbose_name='Departamento'),
        ),
        migrations.CreateModel(
            name='HistoricoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('admissao', 'Admissao'), ('promocao', 'Promocao'), ('transferencia', 'Transferencia de departamento'), ('reajuste', 'Reajuste salarial'), ('afastamento', 'Afastamento'), ('retorno', 'Retorno de afastamento'), ('desligamento', 'Desligamento')], max_length=15, verbose_name='Tipo de evento')),
                ('cargo_anterior', models.CharField(blank=True, max_length=100, verbose_name='Cargo anterior')),
                ('cargo_novo', models.CharField(blank=True, max_length=100, verbose_name='Cargo novo')),
                ('departamento_anterior', models.CharField(blank=True, max_length=100, verbose_name='Departamento anterior')),
                ('departamento_novo', models.CharField(blank=True, max_length=100, verbose_name='Departamento novo')),
                ('remuneracao_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Remuneracao anterior')),
                ('remuneracao_nova', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Remuneracao nova')),
                ('observacao', models.TextField(blank=True, verbose_name='Observacao')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='rh.colaborador', verbose_name='Colaborador')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_rh_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Historico do colaborador',
                'verbose_name_plural': 'Historicos dos colaboradores',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='cargo',
            unique_together={('nome', 'departamento')},
        ),
    ]
