# Generated by Django 5.2.12 on 2026-03-27 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AddField(
            model_name='departamento',
            name='icone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Icone'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='ordem',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordem na sidebar'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Identificador'),
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setores', to='rh.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['departamento__nome', 'nome'],
                'unique_together': {('nome', 'departamento')},
            },
        ),
        migrations.AddField(
            model_name='colaborador',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='rh.setor', verbose_name='Setor'),
        ),
    ]
