# Generated by Django 5.2.12 on 2026-03-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_seed_departamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Identificador'),
        ),
    ]
