# Generated by Django 5.2.12 on 2026-03-27 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_seed_departamentos_extras'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contrato_clt', 'Contrato de trabalho'), ('contrato_pj', 'Contrato de prestacao de servicos'), ('nda', 'NDA / Confidencialidade'), ('aditivo', 'Aditivo contratual'), ('exame_admissional', 'Exame admissional'), ('exame_demissional', 'Exame demissional'), ('termo_rescisao', 'Termo de rescisao'), ('distrato', 'Distrato'), ('certificado', 'Certificado / Diploma'), ('outro', 'Outro documento')], max_length=20, verbose_name='Tipo de documento')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome / Descricao')),
                ('arquivo', models.FileField(upload_to='rh/documentos/%Y/%m/', verbose_name='Arquivo')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de emissao')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de vencimento')),
                ('alerta_dias_antes', models.PositiveSmallIntegerField(default=30, verbose_name='Alertar X dias antes do vencimento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observacao')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='rh.colaborador', verbose_name='Colaborador')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_rh_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Documento do colaborador',
                'verbose_name_plural': 'Documentos dos colaboradores',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluido em')),
                ('colaborador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='rh.colaborador', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Onboarding do colaborador',
                'verbose_name_plural': 'Onboardings dos colaboradores',
            },
        ),
        migrations.CreateModel(
            name='OnboardingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('antes', 'Antes do 1o dia'), ('primeiro_dia', 'Primeiro dia'), ('primeira_semana', 'Primeira semana'), ('primeiro_mes', 'Primeiro mes')], max_length=20, verbose_name='Fase')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descricao')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluido')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluido em')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='rh.onboardingcolaborador', verbose_name='Onboarding')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_itens_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsavel')),
            ],
            options={
                'verbose_name': 'Item do onboarding',
                'verbose_name_plural': 'Itens do onboarding',
                'ordering': ['fase', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do template')),
                ('tipo_contrato', models.CharField(blank=True, choices=[('clt', 'CLT'), ('pj', 'PJ')], help_text='Deixe vazio para ambos os tipos', max_length=3, verbose_name='Tipo de contrato')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(blank=True, help_text='Deixe vazio para todos os departamentos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_templates', to='rh.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Template de onboarding',
                'verbose_name_plural': 'Templates de onboarding',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='onboardingcolaborador',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instancias', to='rh.onboardingtemplate', verbose_name='Template usado'),
        ),
        migrations.CreateModel(
            name='OnboardingTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('antes', 'Antes do 1o dia'), ('primeiro_dia', 'Primeiro dia'), ('primeira_semana', 'Primeira semana'), ('primeiro_mes', 'Primeiro mes')], max_length=20, verbose_name='Fase')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descricao da tarefa')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='rh.onboardingtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Item do template',
                'verbose_name_plural': 'Itens do template',
                'ordering': ['fase', 'ordem'],
            },
        ),
    ]
