# Generated by Django 5.2.12 on 2026-03-27 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0006_documentos_onboarding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do treinamento')),
                ('tipo', models.CharField(choices=[('tecnico_interno', 'Tecnico interno'), ('tecnico_externo', 'Tecnico externo'), ('comportamental', 'Comportamental'), ('compliance', 'Compliance'), ('onboarding', 'Onboarding')], max_length=20, verbose_name='Tipo')),
                ('modalidade', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('hibrido', 'Hibrido')], default='online', max_length=12, verbose_name='Modalidade')),
                ('carga_horaria', models.PositiveSmallIntegerField(default=1, verbose_name='Carga horaria (h)')),
                ('instituicao', models.CharField(blank=True, max_length=200, verbose_name='Instituicao / Plataforma')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='Obrigatorio')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Treinamento',
                'verbose_name_plural': 'Treinamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SaldoFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField(verbose_name='Inicio do periodo aquisitivo')),
                ('periodo_fim', models.DateField(verbose_name='Fim do periodo aquisitivo')),
                ('dias_direito', models.PositiveSmallIntegerField(default=30, verbose_name='Dias de direito')),
                ('dias_usufruidos', models.PositiveSmallIntegerField(default=0, verbose_name='Dias usufruidos')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_ferias', to='rh.colaborador', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Saldo de ferias',
                'verbose_name_plural': 'Saldos de ferias',
                'ordering': ['-periodo_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ferias', 'Ferias'), ('recesso', 'Recesso (PJ)'), ('atestado', 'Atestado medico'), ('licenca_maternidade', 'Licenca maternidade'), ('licenca_paternidade', 'Licenca paternidade'), ('folga_compensatoria', 'Folga compensatoria'), ('falta_justificada', 'Falta justificada'), ('falta_injustificada', 'Falta injustificada')], max_length=25, verbose_name='Tipo de ausencia')),
                ('data_inicio', models.DateField(verbose_name='Data inicio')),
                ('data_fim', models.DateField(verbose_name='Data fim')),
                ('total_dias', models.PositiveSmallIntegerField(verbose_name='Total de dias')),
                ('observacao', models.TextField(blank=True, verbose_name='Observacao')),
                ('status', models.CharField(choices=[('solicitada', 'Solicitada'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=12, verbose_name='Status')),
                ('justificativa_rejeicao', models.TextField(blank=True, verbose_name='Justificativa da rejeicao')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausencias_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado/Rejeitado por')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to='rh.colaborador', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Solicitacao de ausencia',
                'verbose_name_plural': 'Solicitacoes de ausencia',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de inicio')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de conclusao')),
                ('status', models.CharField(choices=[('inscrito', 'Inscrito'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], default='inscrito', max_length=15, verbose_name='Status')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota / Aprovacao')),
                ('certificado', models.FileField(blank=True, upload_to='rh/certificados/%Y/%m/', verbose_name='Certificado')),
                ('observacao', models.TextField(blank=True, verbose_name='Observacao')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinamentos', to='rh.colaborador', verbose_name='Colaborador')),
                ('treinamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='rh.treinamento', verbose_name='Treinamento')),
            ],
            options={
                'verbose_name': 'Participacao em treinamento',
                'verbose_name_plural': 'Participacoes em treinamentos',
                'ordering': ['-criado_em'],
                'unique_together': {('colaborador', 'treinamento')},
            },
        ),
    ]
