# Generated by Django 5.2.12 on 2026-03-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_ferias_treinamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoausencia',
            name='tipo',
            field=models.CharField(choices=[('ferias', 'Ferias'), ('recesso', 'Recesso (PJ)'), ('atestado', 'Atestado medico'), ('licenca_maternidade', 'Licenca maternidade'), ('licenca_paternidade', 'Licenca paternidade'), ('folga_compensatoria', 'Folga compensatoria'), ('luto', 'Luto (falecimento)'), ('nupciais', 'Licenca nupcial (casamento)'), ('falta_justificada', 'Falta justificada'), ('falta_injustificada', 'Falta injustificada')], max_length=25, verbose_name='Tipo de ausencia'),
        ),
    ]
