# Generated by Django 5.2.12 on 2026-03-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_ausencia_luto_nupciais'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='rh/fotos/%Y/%m/', verbose_name='Foto'),
        ),
    ]
