# Generated by Django 5.2.12 on 2026-03-27 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0009_colaborador_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do ciclo')),
                ('periodo_inicio', models.DateField(verbose_name='Inicio do periodo')),
                ('periodo_fim', models.DateField(verbose_name='Fim do periodo')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('encerrado', 'Encerrado')], default='aberto', max_length=15, verbose_name='Status')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ciclo de avaliacao',
                'verbose_name_plural': 'Ciclos de avaliacao',
                'ordering': ['-periodo_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PesquisaENPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('data_inicio', models.DateField(verbose_name='Data de inicio')),
                ('data_encerramento', models.DateField(verbose_name='Data de encerramento')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativa', 'Ativa'), ('encerrada', 'Encerrada')], default='rascunho', max_length=12, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pesquisa eNPS',
                'verbose_name_plural': 'Pesquisas eNPS',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descricao da meta')),
                ('indicador', models.CharField(max_length=200, verbose_name='Indicador de medicao')),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da meta')),
                ('valor_realizado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor realizado')),
                ('peso', models.PositiveSmallIntegerField(default=100, verbose_name='Peso (%)')),
                ('observacao', models.TextField(blank=True, verbose_name='Observacao')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='rh.cicloavaliacao', verbose_name='Ciclo')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='rh.colaborador', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['-peso'],
            },
        ),
        migrations.CreateModel(
            name='PDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=200, verbose_name='Competencia / Area de desenvolvimento')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('observacao', models.TextField(blank=True, verbose_name='Observacao')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdis', to='rh.colaborador', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'PDI',
                'verbose_name_plural': 'PDIs',
                'ordering': ['-ano', 'competencia'],
            },
        ),
        migrations.CreateModel(
            name='AcaoPDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descricao da acao')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('responsavel', models.CharField(blank=True, help_text='Colaborador, gestor ou RH', max_length=100, verbose_name='Responsavel')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluido')], default='pendente', max_length=15, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('treinamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_pdi', to='rh.treinamento', verbose_name='Treinamento vinculado')),
                ('pdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='rh.pdi', verbose_name='PDI')),
            ],
            options={
                'verbose_name': 'Acao do PDI',
                'verbose_name_plural': 'Acoes do PDI',
                'ordering': ['prazo', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaENPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500, verbose_name='Pergunta')),
                ('tipo', models.CharField(choices=[('enps', 'eNPS (0-10)'), ('escala', 'Escala (1-10)'), ('aberta', 'Aberta (texto)')], max_length=10, verbose_name='Tipo')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='rh.pesquisaenps', verbose_name='Pesquisa')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='RespostaENPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nota')),
                ('texto', models.TextField(blank=True, verbose_name='Resposta aberta')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_enps', to='rh.colaborador', verbose_name='Colaborador')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='rh.perguntaenps', verbose_name='Pergunta')),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='rh.pesquisaenps', verbose_name='Pesquisa')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'unique_together': {('colaborador', 'pergunta')},
            },
        ),
    ]
