# Generated by Django 5.2.12 on 2026-03-27 00:25

import apps.crm.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=20, verbose_name='Numero')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Endereco',
                'verbose_name_plural': 'Enderecos',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('tier', models.CharField(choices=[('basico', 'Basico'), ('intermediario', 'Intermediario'), ('avancado', 'Avancado')], default='basico', max_length=20, verbose_name='Tier')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome / Razao Social')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('status', models.CharField(choices=[('recebida', 'Recebida'), ('em_analise', 'Em Analise'), ('em_processamento', 'Em Processamento'), ('concluida', 'Concluida'), ('falha_implantacao', 'Falha na Implantacao'), ('perdida', 'Perdida')], default='recebida', max_length=20)),
                ('arquivo', models.FileField(upload_to=apps.crm.models.upload_cliente_path, verbose_name='Produtos ou Servicos')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_operados', to=settings.AUTH_USER_MODEL)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='crm.endereco', verbose_name='Endereco')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ClienteHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=[('recebida', 'Recebida'), ('em_analise', 'Em Analise'), ('em_processamento', 'Em Processamento'), ('concluida', 'Concluida'), ('falha_implantacao', 'Falha na Implantacao'), ('perdida', 'Perdida')], max_length=20)),
                ('status_novo', models.CharField(choices=[('recebida', 'Recebida'), ('em_analise', 'Em Analise'), ('em_processamento', 'Em Processamento'), ('concluida', 'Concluida'), ('falha_implantacao', 'Falha na Implantacao'), ('perdida', 'Perdida')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='crm.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historico do Cliente',
                'verbose_name_plural': 'Historicos de Clientes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EntidadeParceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_entidade', models.CharField(max_length=200, verbose_name='Nome da entidade')),
                ('percentual_comissao', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Percentual de comissao (%)')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parceiro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entidade Parceira',
                'verbose_name_plural': 'Entidades Parceiras',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='parceiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='crm.entidadeparceira'),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cliente_novo', 'Novo cliente cadastrado'), ('cliente_status', 'Status do cliente alterado'), ('cliente_zypher_ok', 'Implantacao concluida'), ('cliente_zypher_falha', 'Falha na implantacao'), ('comissao_gerada', 'Comissao gerada'), ('comissao_paga', 'Comissao paga'), ('usuario_criado', 'Novo usuario criado'), ('sistema', 'Sistema')], default='sistema', max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacao',
                'verbose_name_plural': 'Notificacoes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do plano')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='crm.entidadeparceira')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='planos',
            field=models.ManyToManyField(related_name='clientes', to='crm.plano', verbose_name='Planos contratados'),
        ),
        migrations.CreateModel(
            name='PlanoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preco')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='crm.plano')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_itens', to='crm.produto')),
            ],
            options={
                'verbose_name': 'Produto do Plano',
                'verbose_name_plural': 'Produtos do Plano',
                'unique_together': {('plano', 'produto')},
            },
        ),
        migrations.AddField(
            model_name='plano',
            name='produtos',
            field=models.ManyToManyField(related_name='planos', through='crm.PlanoProduto', to='crm.produto'),
        ),
    ]
