# Generated by Django 6.0.3 on 2026-03-26 00:02

import apps.crm.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereco')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('produto_interesse', models.CharField(choices=[('agentes_ia', 'Agentes de IA'), ('saas', 'SaaS'), ('crm', 'CRM'), ('erp', 'ERP'), ('sites', 'Sites'), ('consultoria', 'Consultoria')], max_length=30)),
                ('status', models.CharField(choices=[('recebida', 'Recebida'), ('em_analise', 'Em Analise'), ('em_processamento', 'Em Processamento'), ('concluida', 'Concluida'), ('perdida', 'Perdida')], default='recebida', max_length=20)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=apps.crm.models.upload_cliente_path, verbose_name='Produtos ou Servicos')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_operados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ClienteHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=[('recebida', 'Recebida'), ('em_analise', 'Em Analise'), ('em_processamento', 'Em Processamento'), ('concluida', 'Concluida'), ('perdida', 'Perdida')], max_length=20)),
                ('status_novo', models.CharField(choices=[('recebida', 'Recebida'), ('em_analise', 'Em Analise'), ('em_processamento', 'Em Processamento'), ('concluida', 'Concluida'), ('perdida', 'Perdida')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='crm.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historico do Cliente',
                'verbose_name_plural': 'Historicos de Clientes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EntidadeParceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_entidade', models.CharField(max_length=200, verbose_name='Nome da entidade')),
                ('percentual_comissao', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Percentual de comissao (%)')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parceiro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entidade Parceira',
                'verbose_name_plural': 'Entidades Parceiras',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='parceiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='crm.entidadeparceira'),
        ),
        migrations.CreateModel(
            name='ProdutoContratado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(choices=[('agentes_ia', 'Agentes de IA'), ('saas', 'SaaS'), ('crm', 'CRM'), ('erp', 'ERP'), ('sites', 'Sites'), ('consultoria', 'Consultoria')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('contratado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='crm.cliente')),
            ],
            options={
                'verbose_name': 'Produto Contratado',
                'verbose_name_plural': 'Produtos Contratados',
                'ordering': ['-contratado_em'],
            },
        ),
    ]
