# Generated by Django 5.2.12 on 2026-03-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('cliente_novo', 'Novo cliente cadastrado'), ('cliente_status', 'Status do cliente alterado'), ('cliente_zypher_ok', 'Implantacao concluida'), ('cliente_zypher_falha', 'Falha na implantacao'), ('comissao_gerada', 'Comissao gerada'), ('comissao_paga', 'Comissao paga'), ('usuario_criado', 'Novo usuario criado'), ('rh_colaborador', 'Colaborador'), ('rh_documento', 'Documento RH'), ('rh_onboarding', 'Onboarding'), ('rh_ausencia', 'Ausencia'), ('rh_treinamento', 'Treinamento'), ('rh_meta', 'Meta/PDI'), ('rh_enps', 'eNPS'), ('sistema', 'Sistema')], default='sistema', max_length=30),
        ),
    ]
