# Generated by Django 6.0.3 on 2026-03-25 23:16

import apps.crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='documento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=300, verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=apps.crm.models.upload_cliente_path, verbose_name='Produtos ou Servicos'),
        ),
    ]
