# Generated by Django 5.2.12 on 2026-03-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_notificacao_tipos_rh'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencianotificacao',
            name='fin_asaas',
            field=models.BooleanField(default=True, verbose_name='Gateway Asaas'),
        ),
        migrations.AddField(
            model_name='preferencianotificacao',
            name='fin_cobranca',
            field=models.BooleanField(default=True, verbose_name='Cobranca / Pagamento'),
        ),
        migrations.AddField(
            model_name='preferencianotificacao',
            name='fin_folha',
            field=models.BooleanField(default=True, verbose_name='Folha de pagamento'),
        ),
        migrations.AddField(
            model_name='preferencianotificacao',
            name='fin_lancamento',
            field=models.BooleanField(default=True, verbose_name='Lancamento financeiro'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('cliente_novo', 'Novo cliente cadastrado'), ('cliente_status', 'Status do cliente alterado'), ('cliente_zypher_ok', 'Implantacao concluida'), ('cliente_zypher_falha', 'Falha na implantacao'), ('comissao_gerada', 'Comissao gerada'), ('comissao_paga', 'Comissao paga'), ('usuario_criado', 'Novo usuario criado'), ('rh_colaborador', 'Colaborador'), ('rh_documento', 'Documento RH'), ('rh_onboarding', 'Onboarding'), ('rh_ausencia', 'Ausencia'), ('rh_treinamento', 'Treinamento'), ('rh_meta', 'Meta/PDI'), ('rh_enps', 'eNPS'), ('fin_lancamento', 'Lancamento financeiro'), ('fin_cobranca', 'Cobranca / Pagamento'), ('fin_folha', 'Folha de pagamento'), ('fin_asaas', 'Gateway Asaas'), ('sistema', 'Sistema')], default='sistema', max_length=30),
        ),
    ]
