# Generated by Django 6.0.3 on 2026-03-25 17:19

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do sistema')),
                ('token', models.CharField(default=secrets.token_hex, max_length=64, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Token de Integração',
                'verbose_name_plural': 'Tokens de Integração',
                'ordering': ['-criado_em'],
            },
        ),
    ]
