# Generated by Django 5.2.12 on 2026-03-29 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criacao', 'Criacao'), ('edicao', 'Edicao'), ('exclusao', 'Exclusao'), ('status', 'Mudanca de status'), ('exportacao', 'Exportacao'), ('webhook', 'Evento externo'), ('sistema', 'Sistema')], max_length=20, verbose_name='Acao')),
                ('departamento', models.CharField(choices=[('financeiro', 'Financeiro'), ('comercial', 'Comercial'), ('rh', 'RH / Pessoas'), ('administracao', 'Administracao'), ('integracao', 'Integracao'), ('sistema', 'Sistema')], db_index=True, max_length=20, verbose_name='Departamento')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descricao')),
                ('detalhes', models.JSONField(blank=True, default=dict, verbose_name='Detalhes')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=300, verbose_name='Representacao')),
                ('fonte', models.CharField(db_index=True, default='interno', help_text='interno, asaas_webhook, api, celery, sistema', max_length=30, verbose_name='Fonte')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de auditoria',
                'verbose_name_plural': 'Logs de auditoria',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['departamento', '-criado_em'], name='auditoria_a_departa_648cb4_idx'), models.Index(fields=['content_type', 'object_id'], name='auditoria_a_content_2f8c97_idx'), models.Index(fields=['usuario', '-criado_em'], name='auditoria_a_usuario_6eebaa_idx'), models.Index(fields=['fonte', '-criado_em'], name='auditoria_a_fonte_9dc17c_idx')],
            },
        ),
    ]
